### ISSUE TITLE
Discrepância entre tabela de mutantes sobreviventes e ficheiro de mutantes sobreviventes

### ISSUE THREAD

**Issue by frpdoliv3** [PedroTav/defects4j#4]
Existe uma discrepância entre os mutantes apresentados na tabela Live Mutant Data e os mutantes presentes no ficheiro CSV especificado na GUI como apresentado na imagem abaixo.

![Screenshot from 2023-11-22 12-22-29](https://github.com/PedroTav/defects4j/assets/124865183/77efef5f-0fdc-44f6-b88c-311107c0cb4f)

Projeto: CLI
Versão: 32f
Ferramenta: Major

[major_mutants.csv](https://github.com/PedroTav/defects4j/files/13441390/major_mutants.csv)

**Comment by PedroTav** [comment]
Obrigado pela informação Francisco. Já descobri qual é o problema. 

Até eu fazer a correção por favor guia-te pelo ficheiro csv gerado pela ferramenta e não uses a tabela gerada pela GUI.

**Comment by PedroTav** [comment]
Francisco, o novo commit já deve corrigir o problema da discrepância entre os valores da tabela. Novamente, obrigado pelo report.

Por favor, se conseguir, confirme do seu lado.

**Comment by jose** [comment]
@frpdoliv3, confirmas que o [fix](https://github.com/PedroTav/defects4j/commit/89886244ac774fcd6a403c3058762f4674b0293c) funciona?

**Comment by frpdoliv3** [comment]
Atualizei o defects4J para a versão mais recente e confirmo que o fix funciona, obrigado.

**Comment by jose** [comment]
@PedroTav, acho que podes fechar esta issue.
